
# ─── Severity badge colors used across app.py ──────────────────
SEVERITY_LEVELS = {
    "None":     ("#00ffa3", "rgba(0,255,163,.08)"),
    "Low":      ("#a3e635", "rgba(163,230,53,.08)"),
    "Medium":   ("#fbbf24", "rgba(251,191,36,.08)"),
    "High":     ("#f97316", "rgba(249,115,22,.08)"),
    "Critical": ("#f43f5e", "rgba(244,63,94,.08)"),
    "Unknown":  ("#64748b", "rgba(100,116,139,.08)"),
}

# ─── Disease Database (keyed exactly by class_mapping.json names) ──
SKIN_DISEASE_DATABASE = {
    "Acne And Rosacea Photos": {
        "name": "Acne & Rosacea",
        "category": "Inflammatory",
        "symptoms": "Pimples, blackheads, whiteheads, facial redness, visible blood vessels, and in rosacea, flushing and bumps mainly on the cheeks and nose.",
        "causes": "Clogged hair follicles from oil and dead skin, bacteria, hormonal changes, and for rosacea, triggers like heat, spicy food, alcohol, and sun exposure.",
        "treatment_topical": "Benzoyl peroxide, topical retinoids, azelaic acid, and topical antibiotics for acne; metronidazole gel for rosacea.",
        "treatment_systemic": "Oral antibiotics, hormonal therapy (in some cases), or isotretinoin for severe acne under dermatologist supervision.",
        "home_remedies": "Gentle cleansing twice daily, non-comedogenic moisturizer, avoiding picking lesions, daily sunscreen.",
        "prevention": "Avoid harsh scrubbing, manage stress, identify and avoid rosacea triggers, keep skin clean and moisturized.",
        "severity": "Low",
        "contagious": False,
        "doctor_visit": "See a dermatologist if breakouts are painful, cystic, scarring, or not improving after 6-8 weeks of OTC treatment.",
    },
    "Atopic Dermatitis Photos": {
        "name": "Atopic Dermatitis (Eczema)",
        "category": "Inflammatory / Autoimmune",
        "symptoms": "Dry, intensely itchy, red, inflamed patches of skin, often in elbow creases, behind knees, and on the face; can ooze or crust when scratched.",
        "causes": "A combination of genetic skin-barrier dysfunction, immune system overactivity, allergens, irritants, and environmental triggers.",
        "treatment_topical": "Topical corticosteroids, calcineurin inhibitors (tacrolimus/pimecrolimus), and frequent emollient use.",
        "treatment_systemic": "Oral antihistamines for itch, and in severe cases, systemic immunomodulators or biologics prescribed by a doctor.",
        "home_remedies": "Lukewarm baths, fragrance-free moisturizer applied within minutes of bathing, soft cotton clothing, humidifier use.",
        "prevention": "Moisturize daily, avoid known triggers (harsh soaps, wool, sudden temperature changes), manage stress.",
        "severity": "Medium",
        "contagious": False,
        "doctor_visit": "Consult a dermatologist if itching disrupts sleep, skin shows signs of infection, or flares are frequent.",
    },
    "Ba  Cellulitis": {
        "name": "Bacterial Cellulitis",
        "category": "Infectious — Bacterial",
        "symptoms": "Red, swollen, warm, and tender area of skin that spreads quickly, sometimes with fever, chills, and skin tightness or blistering.",
        "causes": "Bacteria (commonly Streptococcus or Staphylococcus) entering through a break in the skin such as a cut, insect bite, or wound.",
        "treatment_topical": "Wound cleaning and dressing; topical antibiotics are generally not sufficient on their own.",
        "treatment_systemic": "Oral or intravenous antibiotics prescribed by a physician, depending on severity.",
        "home_remedies": "Elevate the affected limb, keep the wound clean, apply a cool compress; not a substitute for antibiotics.",
        "prevention": "Clean and cover cuts promptly, manage chronic conditions like diabetes, moisturize to prevent skin cracking.",
        "severity": "High",
        "contagious": False,
        "doctor_visit": "Seek medical care promptly — cellulitis can spread rapidly and lead to serious complications if untreated.",
    },
    "Ba Impetigo": {
        "name": "Bacterial Impetigo",
        "category": "Infectious — Bacterial",
        "symptoms": "Red sores, often around the nose and mouth, that quickly rupture, ooze, and form a characteristic honey-colored crust.",
        "causes": "Staphylococcus aureus or Streptococcus pyogenes bacteria infecting the skin, often through minor cuts, insect bites, or close contact.",
        "treatment_topical": "Topical antibiotic ointment such as mupirocin for localized cases.",
        "treatment_systemic": "Oral antibiotics for widespread or severe impetigo.",
        "home_remedies": "Gently wash crusts with mild soap and water, keep the area clean and covered, avoid scratching.",
        "prevention": "Good hand hygiene, avoid sharing towels or razors, promptly clean minor skin injuries.",
        "severity": "Medium",
        "contagious": True,
        "doctor_visit": "See a doctor for proper antibiotic treatment, especially in children, since impetigo is highly contagious.",
    },
    "Benign": {
        "name": "Benign Skin Lesion",
        "category": "Benign Growth",
        "symptoms": "Well-defined, slow-growing, symmetric growth with even color and stable size and shape over time; usually painless.",
        "causes": "Normal proliferation of skin cells, sun exposure, aging, or genetic predisposition; not cancerous.",
        "treatment_topical": "Generally no treatment required unless for cosmetic reasons.",
        "treatment_systemic": "Not typically needed.",
        "home_remedies": "Monitor for any changes in size, shape, or color using the ABCDE rule; protect from sun exposure.",
        "prevention": "Regular skin self-exams and sunscreen use to limit new growths.",
        "severity": "None",
        "contagious": False,
        "doctor_visit": "Have any new or changing growth evaluated by a dermatologist to confirm it is benign.",
    },
    "Fu Athlete Foot": {
        "name": "Athlete's Foot (Tinea Pedis)",
        "category": "Infectious — Fungal",
        "symptoms": "Itchy, scaly, cracked skin between the toes and on the soles, sometimes with redness, burning, and blisters.",
        "causes": "Dermatophyte fungal infection thriving in warm, moist environments like shoes, socks, and locker rooms.",
        "treatment_topical": "Antifungal creams or sprays such as clotrimazole, terbinafine, or miconazole.",
        "treatment_systemic": "Oral antifungal medication for severe or persistent infections.",
        "home_remedies": "Keep feet clean and dry, change socks daily, use antifungal foot powder, wear breathable footwear.",
        "prevention": "Avoid walking barefoot in communal showers, dry feet thoroughly after washing, rotate shoes.",
        "severity": "Low",
        "contagious": True,
        "doctor_visit": "See a doctor if the infection spreads, doesn't improve with OTC treatment, or you have diabetes.",
    },
    "Fu Nail Fungus": {
        "name": "Fungal Nail Infection (Onychomycosis)",
        "category": "Infectious — Fungal",
        "symptoms": "Thickened, discolored (yellow/brown), brittle, or crumbling nails, sometimes with a foul odor.",
        "causes": "Dermatophyte or yeast fungi invading the nail bed, often spreading from athlete's foot.",
        "treatment_topical": "Antifungal nail lacquer applied regularly over several months.",
        "treatment_systemic": "Oral antifungal medications for moderate-to-severe infections, prescribed after liver function checks.",
        "home_remedies": "Keep nails trimmed and dry, avoid nail polish over infected nails, disinfect nail tools.",
        "prevention": "Wear moisture-wicking socks, avoid sharing nail clippers, treat athlete's foot promptly.",
        "severity": "Low",
        "contagious": True,
        "doctor_visit": "Consult a doctor if home treatment fails after several months or the infection is painful.",
    },
    "Fu Ringworm": {
        "name": "Ringworm (Tinea Corporis)",
        "category": "Infectious — Fungal",
        "symptoms": "Itchy, circular, red rash with a raised, scaly border and clearer skin in the center, giving a ring-like appearance.",
        "causes": "Dermatophyte fungi spread through skin-to-skin contact, contaminated surfaces, or infected animals.",
        "treatment_topical": "Antifungal creams such as clotrimazole or terbinafine applied to the affected area.",
        "treatment_systemic": "Oral antifungals for widespread or stubborn infections.",
        "home_remedies": "Keep the area clean and dry, avoid sharing clothing or towels, wash bedding frequently.",
        "prevention": "Avoid contact with infected people/pets, practice good hygiene, dry skin thoroughly after sweating.",
        "severity": "Low",
        "contagious": True,
        "doctor_visit": "See a doctor if the rash spreads, doesn't respond to OTC antifungals, or recurs frequently.",
    },
    "Hair Loss Photos Alopecia And Other Hair Diseases": {
        "name": "Alopecia & Hair Loss Disorders",
        "category": "Inflammatory / Autoimmune",
        "symptoms": "Gradual thinning, patchy bald spots, or sudden hair shedding, sometimes with scalp redness or itching.",
        "causes": "Genetics, autoimmune attack on hair follicles, hormonal changes, stress, nutritional deficiency, or scalp conditions.",
        "treatment_topical": "Topical minoxidil and corticosteroid solutions for certain types of hair loss.",
        "treatment_systemic": "Oral medications, corticosteroid injections, or other therapies depending on diagnosed cause.",
        "home_remedies": "Gentle hair care, balanced diet rich in iron and protein, avoiding tight hairstyles and heat damage.",
        "prevention": "Manage underlying health conditions, reduce stress, avoid excessive heat/chemical styling.",
        "severity": "Low",
        "contagious": False,
        "doctor_visit": "Consult a dermatologist for sudden, patchy, or rapidly progressing hair loss to identify the cause.",
    },
    "Heathy": {
        "name": "Healthy Skin",
        "category": "Normal",
        "symptoms": "No visible lesions, even tone and texture, no abnormal redness, scaling, or growths.",
        "causes": "Not applicable — this represents normal, healthy skin.",
        "treatment_topical": "Not applicable.",
        "treatment_systemic": "Not applicable.",
        "home_remedies": "Maintain a regular skincare routine: gentle cleansing, moisturizing, and daily sunscreen.",
        "prevention": "Stay hydrated, eat a balanced diet, protect skin from excessive sun exposure.",
        "severity": "None",
        "contagious": False,
        "doctor_visit": "Routine annual skin checks are still recommended, especially with a family history of skin cancer.",
    },
    "Herpes Hpv And Other Stds Photos": {
        "name": "Herpes, HPV & Other STD-Related Skin Conditions",
        "category": "Infectious — Viral",
        "symptoms": "Painful blisters or sores (herpes), warts (HPV), or other lesions in the genital or oral area, sometimes with itching, tingling, or burning.",
        "causes": "Viral infections (HSV, HPV) transmitted primarily through skin-to-skin or sexual contact.",
        "treatment_topical": "Topical antiviral creams or wart-removal treatments depending on diagnosis.",
        "treatment_systemic": "Oral antiviral medication for herpes outbreaks; HPV vaccination is preventive, not curative.",
        "home_remedies": "Keep area clean and dry, avoid touching/scratching lesions, use over-the-counter pain relief as needed.",
        "prevention": "Practice safe sex, get vaccinated against HPV, avoid contact with active lesions.",
        "severity": "Medium",
        "contagious": True,
        "doctor_visit": "See a healthcare provider promptly for diagnosis and treatment; these conditions require professional confirmation.",
    },
    "Malignant": {
        "name": "Malignant Skin Lesion",
        "category": "Malignant Tumor",
        "symptoms": "Asymmetric, irregular-bordered, multi-colored, or rapidly changing/growing lesion, possibly bleeding, itching, or ulcerating.",
        "causes": "Uncontrolled growth of abnormal skin cells, strongly linked to UV exposure, genetics, and immune suppression.",
        "treatment_topical": "Not appropriate as primary treatment — requires medical/surgical management.",
        "treatment_systemic": "Surgical excision, and depending on type/stage, chemotherapy, immunotherapy, or radiation under oncology care.",
        "home_remedies": "None — this requires immediate professional medical evaluation, not home treatment.",
        "prevention": "Sun protection, regular skin self-exams, avoiding tanning beds, early professional evaluation of suspicious lesions.",
        "severity": "Critical",
        "contagious": False,
        "doctor_visit": "Seek immediate evaluation by a dermatologist or oncologist — early diagnosis significantly improves outcomes.",
    },
    "Melanoma Skin Cancer Nevi And Moles": {
        "name": "Melanoma, Skin Cancer, Nevi & Moles",
        "category": "Malignant Tumor",
        "symptoms": "Moles or spots showing Asymmetry, irregular Border, varied Color, Diameter over 6mm, or Evolving size/shape (ABCDE rule).",
        "causes": "DNA damage in melanocytes from UV radiation, genetic predisposition, and high mole/sun-exposure history.",
        "treatment_topical": "Not appropriate for confirmed melanoma — requires surgical and oncologic treatment.",
        "treatment_systemic": "Surgical removal, and depending on stage, immunotherapy, targeted therapy, or chemotherapy.",
        "home_remedies": "None — monitor moles regularly using the ABCDE rule and seek prompt evaluation for changes.",
        "prevention": "Daily sunscreen, avoid peak sun hours and tanning beds, routine dermatologist mole mapping.",
        "severity": "Critical",
        "contagious": False,
        "doctor_visit": "Any new, changing, or unusual mole should be evaluated by a dermatologist immediately.",
    },
    "Nail Fungus And Other Nail Disease": {
        "name": "Nail Fungus & Other Nail Diseases",
        "category": "Infectious — Fungal",
        "symptoms": "Discolored, thickened, brittle, or separated nails; may include ridges, pitting, or partial nail loss.",
        "causes": "Fungal or yeast infection, trauma, psoriasis, or other underlying nail-bed conditions.",
        "treatment_topical": "Antifungal or medicated nail lacquers, depending on underlying cause.",
        "treatment_systemic": "Oral antifungals or treatment of the underlying systemic condition (e.g., psoriasis therapy).",
        "home_remedies": "Keep nails clean, dry, and trimmed; avoid trauma and tight-fitting shoes.",
        "prevention": "Good foot/hand hygiene, breathable footwear, prompt treatment of minor nail injuries.",
        "severity": "Low",
        "contagious": True,
        "doctor_visit": "Consult a doctor if nail changes persist, worsen, or are painful to determine the exact cause.",
    },
    "Pa Cutaneous Larva Migrans": {
        "name": "Cutaneous Larva Migrans",
        "category": "Infectious — Parasitic",
        "symptoms": "Intensely itchy, raised, winding (serpiginous) red track on the skin that slowly advances over days.",
        "causes": "Hookworm larvae (commonly from animal feces in soil or sand) penetrating and migrating through the skin.",
        "treatment_topical": "Topical antiparasitic agents such as thiabendazole cream for localized lesions.",
        "treatment_systemic": "Oral antiparasitic medication such as albendazole or ivermectin, prescribed by a physician.",
        "home_remedies": "Avoid scratching to prevent secondary bacterial infection; keep the area clean.",
        "prevention": "Wear footwear on beaches/soil in endemic areas, avoid direct skin contact with contaminated sand.",
        "severity": "Medium",
        "contagious": False,
        "doctor_visit": "See a doctor for antiparasitic treatment — the condition will not resolve without medication.",
    },
    "Rashes": {
        "name": "General Skin Rash",
        "category": "Inflammatory",
        "symptoms": "Red, irritated, sometimes itchy or bumpy skin that can vary widely in pattern, distribution, and texture.",
        "causes": "Allergic reactions, irritants, infections, heat, autoimmune conditions, or contact with certain substances.",
        "treatment_topical": "Mild topical corticosteroids or antihistamine creams depending on the cause.",
        "treatment_systemic": "Oral antihistamines or other medication if the rash is widespread or allergy-related.",
        "home_remedies": "Cool compresses, fragrance-free moisturizer, avoiding known irritants, loose breathable clothing.",
        "prevention": "Identify and avoid triggers, patch-test new products, maintain skin barrier health.",
        "severity": "Low",
        "contagious": False,
        "doctor_visit": "See a doctor if the rash is widespread, painful, blistering, or accompanied by fever.",
    },
    "Urticaria Hives": {
        "name": "Urticaria (Hives)",
        "category": "Inflammatory",
        "symptoms": "Raised, itchy, red or skin-colored welts that can appear suddenly and move around the body, often resolving within 24 hours each.",
        "causes": "Allergic reactions to food, medication, insect stings, or non-allergic triggers like stress, heat, or pressure.",
        "treatment_topical": "Calamine lotion or cool compresses for symptomatic relief.",
        "treatment_systemic": "Oral antihistamines; severe cases may need corticosteroids or epinephrine if anaphylaxis is suspected.",
        "home_remedies": "Avoid known triggers, wear loose clothing, apply a cool compress to reduce itching.",
        "prevention": "Identify and avoid allergens/triggers, manage stress, carry antihistamines if prone to flare-ups.",
        "severity": "Medium",
        "contagious": False,
        "doctor_visit": "Seek immediate care if hives are accompanied by swelling of the face/throat or difficulty breathing.",
    },
    "Vasculitis Photos": {
        "name": "Vasculitis",
        "category": "Inflammatory / Autoimmune",
        "symptoms": "Purplish or reddish spots (purpura), bumps, or ulcers on the skin, sometimes with fever, joint pain, or fatigue.",
        "causes": "Inflammation of blood vessels due to autoimmune disease, infection, medication reaction, or unknown triggers.",
        "treatment_topical": "Not typically sufficient alone — supportive wound care for skin ulcers if present.",
        "treatment_systemic": "Corticosteroids or immunosuppressive medication prescribed by a specialist based on underlying cause.",
        "home_remedies": "Rest, elevate affected limbs, avoid known triggering medications until evaluated.",
        "prevention": "Manage underlying autoimmune or infectious conditions; avoid known triggering drugs.",
        "severity": "High",
        "contagious": False,
        "doctor_visit": "Seek prompt medical evaluation — vasculitis can involve internal organs and needs proper diagnosis.",
    },
    "Vi Chickenpox": {
        "name": "Chickenpox (Varicella)",
        "category": "Infectious — Viral",
        "symptoms": "Itchy, fluid-filled blisters appearing in crops over the body, often with fever and fatigue, eventually crusting over.",
        "causes": "Varicella-zoster virus, spread through respiratory droplets or direct contact with blister fluid.",
        "treatment_topical": "Calamine lotion and oatmeal baths to relieve itching.",
        "treatment_systemic": "Antiviral medication (e.g., acyclovir) in high-risk individuals; antihistamines for itch; fever reducers as needed.",
        "home_remedies": "Keep nails trimmed to avoid scratching, lukewarm baths, light loose clothing.",
        "prevention": "Varicella vaccination; avoid close contact with infected individuals until lesions fully crust.",
        "severity": "Medium",
        "contagious": True,
        "doctor_visit": "See a doctor for high fever, signs of skin infection, or if a high-risk individual (pregnant, immunocompromised) is affected.",
    },
    "Vi Shingles": {
        "name": "Shingles (Herpes Zoster)",
        "category": "Infectious — Viral",
        "symptoms": "Painful, burning rash with blisters typically appearing in a band on one side of the body, often preceded by tingling pain.",
        "causes": "Reactivation of the dormant varicella-zoster virus, often triggered by stress, illness, or weakened immunity.",
        "treatment_topical": "Calamine lotion and cool compresses for symptomatic relief.",
        "treatment_systemic": "Antiviral medication (acyclovir, valacyclovir) started early, plus pain management as needed.",
        "home_remedies": "Keep the rash clean and covered, wear loose clothing, avoid contact with at-risk individuals until crusted.",
        "prevention": "Shingles vaccination, especially for adults over 50 or those with weakened immune systems.",
        "severity": "High",
        "contagious": True,
        "doctor_visit": "See a doctor promptly — early antiviral treatment within 72 hours significantly reduces complications.",
    },
}


def get_disease_info(class_name):
    """Return the info dict for a given class name, or None if not found."""
    return SKIN_DISEASE_DATABASE.get(class_name)
